### PR TITLE
changed the styling for the scroll history buttons

### LINKED ISSUE #15: Scroll History
Each move made by the players will be recorded with the addition of this feature.

### PR DESCRIPTION
**Pull request by yalihuss**

### CODE REVIEW

**Review by khanh0097 — COMMENTED** [review]
hussain

Great work @yalihuss. UI is looking good now. It is just a suggestion to remove these `li` numbers on the left. Also adding space between button would be nicer.

**Comment by yalihuss** [comment]
All styling changes done. @khanh0097 thanks for the suggestions, UI is looking great now.

**Review by khanh0097 — APPROVED** [review]
Thanks for the prompt response @yalihuss. This looks better now.

**Review by NivedhaSrinivasan09 — APPROVED** [review]
Looks fine

**Pull request merged**
